version: '3'

services:
    nginx:
        build: ./docker-conf/nginx/
        ports:
            - 8003:80
        links:
            - php
        volumes:
            - .:/var/www/html
        environment:
            - VIRTUAL_HOST=interview.localhost
        networks:
            - backend

    php:
        build: ./docker-conf/php/
        links:
            - postgres
            - postgres-test
        expose:
            - 9000
        volumes:
            - .:/var/www/html
            - ./docker-conf/php/conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker-conf/php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/custom.conf
        environment:
            PHP_IDE_CONFIG: "serverName=interview"
        networks:
            - backend

    postgres:
        image: postgres:14.2
        container_name: postgres
        ports:
            - 54324:5432
        volumes:
            - /var/lib/postgresql
        environment:
            POSTGRES_USER: interview
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: interview_db.db
        networks:
            - backend

    postgres-test:
        image: postgres:14.2
        container_name: postgres-test
        ports:
            - 54325:5432
        volumes:
            - /var/lib/postgresql
        environment:
            POSTGRES_USER: interview_test
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: interview-test_db.db
        networks:
            - backend


networks:
    backend:
